# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def fibonacci():
    first = 1
    second = 2
    new = 0
    fibonacci_list = list([1,2])
    while (new <= 4000000):
        new = first + second
        fibonacci_list.append(new)
        first,second = second,new
    return fibonacci_list

total = 0
for i in fibonacci():
    if (i%2 == 0):
        total +=i
print(total)
        
